name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  main_job:
    name: Main job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build and restore
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 8.0.x
    - run: |
        dotnet restore
        dotnet build --no-restore --configuration Release

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ricardokcavati
        password: ${{ secrets.DOCKERHUB }}
